apiVersion: v1
kind: ConfigMap
metadata:
  name: initcontainer-config
  namespace: mutate-webhook
data:
  init-container.yaml: |
    containers:
      - name: myapp-container
        image: busybox:1.28
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
