apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-config
  labels:
    app: init-container-injector
webhooks:
  - name: mutate-server-svc.mutate-webhook.svc
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: mutate-server-svc
        namespace: mutate-webhook
        path: "/mutate"
      caBundle: "${CA_BUNDLE}"
    rules:
    - operations: ["CREATE"]
      apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments"]