apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: katib-job-webhook-cert
  namespace: kubeflow
  labels:
    some-annotation: "true"
spec:
  secretName: katib-job-webhook-tls
  duration: 2880h
  renewBefore: 360h
  dnsNames:
    - katib-job-webhook-svc.kubeflow.svc
    - katib-job-webhook-svc.kubeflow.svc.cluster.local    
    - katib-job-webhook-svc    
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: ck-selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io