apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: annotation-injector-for-katib-cert
  namespace: kubeflow
  labels:
    some-annotation: "true"
spec:
  secretName: annotation-injector-for-katib-tls
  duration: 2880h
  renewBefore: 360h
  dnsNames:
    - annotation-injector-for-pod-svc.kubeflow.svc
    - annotation-injector-for-pod-svc.kubeflow.svc.cluster.local    
    - annotation-injector-for-pod-svc  
    - annotation-injector-for-job-svc.kubeflow.svc
    - annotation-injector-for-job-svc.kubeflow.svc.cluster.local    
    - annotation-injector-for-job-svc   
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: ck-selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io