apiVersion: v1
kind: ServiceAccount
metadata:
  name: katib-resource-reader
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-katib-reader
rules:
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch", "update" ]  
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods" ]
    verbs: [ "get", "list", "watch", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-katib-resource
subjects:
  - kind: ServiceAccount
    name: katib-resource-reader
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-katib-reader
