apiVersion: v1
kind: ServiceAccount
metadata:
  name: katib-job-reader
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-reader
rules:
  - apiGroups: [ "batch" ]
    resources: [ "job" ]
    verbs: [ "get", "list", "watch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods" ]
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-job
subjects:
  - kind: ServiceAccount
    name: katib-job-reader
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-reader
