apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    hypercloud: annotation-inject
  name: annotation-injector-for-katib
  namespace: kubeflow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      hypercloud: annotation-inject
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        hypercloud: annotation-inject
    spec:
      serviceAccountName: katib-resource-reader
      containers:
      - env:
        - name: TZ
          value: Asia/Seoul
        image: kitaeyoo777/katib-anno-webhook:v1.0.0
        imagePullPolicy: Always
        name: annotation-injector-for-katib
        ports:
        - containerPort: 8443
          name: webhook
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/secrets/tls
          name: annotation-injector-for-katib-tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: annotation-injector-for-katib-tls
        secret:
          defaultMode: 420
          secretName: annotation-injector-for-katib-tls
