apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: katib-job-webhook-mutator
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/katib-job-webhook-cert
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: katib-job-webhook-svc
      namespace: kubeflow
      path: /api/webhook/add-annotation/job 
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: katib-job-webhook-svc.kubeflow.svc
  namespaceSelector:
    matchExpressions:
    - key: job-webhook
      operator: NotIn
      values:
      - "false"
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: katib-job-webhook-svc
      namespace: kubeflow
      path: /api/webhook/add-annotation/job 
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: katib-job-webhook-svc.kubeflow.svc
  namespaceSelector:
    matchExpressions:
    - key: job-webhook
      operator: NotIn
      values:
      - "false"
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tfjobs
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10  