apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: katib-experiment-webhook-mutator
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/katib-experiment-webhook-cert
webhooks:
  - admissionReviewVersions:
      - v1beta1      
    name: katib-experiment-webhook-svc.kubeflow.svc
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: trainedmodel-webhook-svc
        namespace: kubeflow
        path: /api/webhook/add-annotation/experiment 
        port: 443
    rules:
      - apiGroups: [ "kubeflow.org" ]
        apiVersions: [ "v1beta1" ]
        resources: [ "experiments" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: '*'
    sideEffects: None