apiVersion: v1
kind: Service
metadata:
  labels:
    hypercloud: annotation-inject
  name: annotation-injector-for-job-svc
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    hypercloud: annotation-inject
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    hypercloud: annotation-inject
  name: annotation-injector-for-pod-svc
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    hypercloud: annotation-inject
  sessionAffinity: None
  type: ClusterIP
