apiVersion: v1
kind: Service
metadata:
  labels:
    hypercloud: job-webhook
  name: katib-job-webhook-svc
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    hypercloud: job-webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    hypercloud: job-webhook
  name: katib-pod-webhook-svc
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    hypercloud: job-webhook
  sessionAffinity: None
  type: ClusterIP
