apiVersion: v1
kind: Service
metadata:
  labels:
    hypercloud: experiment-webhook
  name: katib-experiment-webhook-svc
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    hypercloud: experiment-webhook
  sessionAffinity: None
  type: ClusterIP

