apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    hypercloud: experiment-webhook
  name: katib-experiment-webhook
  namespace: kubeflow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      hypercloud: experiment-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        hypercloud: experiment-webhook
    spec:
      serviceAccountName: katib-experiment-reader
      containers:
      - env:
        - name: TZ
          value: Asia/Seoul
        image: kitaeyoo777/ex-test:test
        imagePullPolicy: Always
        name: katib-experiment-webhook
        ports:
        - containerPort: 8443
          name: webhook
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/secrets/tls
          name: katib-experiement-webhook-tls
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: katib-experiement-webhook-tls
        secret:
          defaultMode: 420
          secretName: katib-experiement-webhook-tls
